EVoteTemplateLINQ/Controllers/RosterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EVote.DataModels;
using EVote.DataMethods;
using EVote.Filters;
using EVote.Extensions;

namespace EVote.Controllers
{
    [VerifyUser]
    public class RosterController : Controller
    {
        ConfigurationModel _Session = ConfigurationMethods.SessionConfigs();

        // GET: Roster
        public ActionResult Index(int? page)
        {
            return View("FullSearch", InitializeRoster(page));
        }

        // Full name at date search page
        public ActionResult FullSearch(int? page)
        {
            return View(InitializeRoster(page));
        }

        // Pull most recent voters page by page
        public IEnumerable<VoterDataModel> InitializeRoster(int? page)
        {
            // Initialize page number
            if (page.IsNull()) page = 1;

            int size = Int32.Parse(Session["PageSize"].ToString()); // Set to session varriable

            IEnumerable<VoterDataModel> voterRoster;

            // Get the list of voters or voters from a specific site
            if (Session["SiteOnlyRoster"].ToString() == "True")
            {
                var site = Session["Username"].ToString();
                voterRoster = VoterDataMethods.RosterBySiteList(site);
            }
            else
            {
                voterRoster = VoterDataMethods.RosterList();
            }

            // Check for empty list
            ViewBag.EmptyList = VoterDataMethods.VoterCount(voterRoster);

            int maxPage = (ViewBag.EmptyList / size) + 1;            

            // set page limits
            if (page < 1) page = 1;
            if (page > maxPage) page = maxPage;

            // Set page counter display
            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = maxPage;

            // Returned a paged list of voters
            if (Session["Registration"].ToString() != "True")
            {
                return voterRoster.OrderByDescending(o => o.LogDate).Skip((int)(page - 1) * size).Take(size);
            }
            else
            {                
                return voterRoster.OrderByDescending(o => o.RegisteredDate).Skip((int)(page - 1) * size).Take(size);
            }                
        }

        // returns the partial view of voters from a full name at date search
        public ActionResult VoterExtendedSearch(string strRoll, string strLastName, string strFirstName, string strDate)
        {
            // Get the list of voters
            IEnumerable<VoterDataModel> voterRoster;
            if (Session["SiteOnlyRoster"].ToString() == "True")
            {
                var site = Session["Username"].ToString();
                voterRoster = VoterDataMethods.RosterSiteSearch(strRoll, strLastName, strFirstName, strDate, site);
            }
            else
            {
                voterRoster = VoterDataMethods.RosterSearch(strRoll, strLastName, strFirstName, strDate);
            }

            // Check for empty list
            ViewBag.EmptyList = VoterDataMethods.VoterCount(voterRoster);

            return PartialView("_List", voterRoster.OrderByDescending(o => o.LogDate));
        }

        public ActionResult VoterModelSearch(VoterSearchModel search)
        {
            // Get the list of voters            
            // Get the list of voters            
            IEnumerable<VoterDataModel> voterRoster;
            if (Session["SiteOnlyRoster"].ToString() == "True")
            {
                var site = Session["Username"].ToString();
                voterRoster = VoterDataMethods.RosterSiteModelSearch(search, site);
            }
            else
            {
                voterRoster = VoterDataMethods.RosterModelSearch(search);
            }

            // Check for empty list
            if (voterRoster != null) ViewBag.EmptyList = voterRoster.Count();
            else ViewBag.EmptyList = 0;

            return PartialView("_List", voterRoster.OrderByDescending(o => o.LogDate));
        }
    }
}

EVoteTemplateLINQ/Controllers/SpoiledController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EVote.DataModels;
using EVote.DataMethods;
using EVote.Filters;

namespace EVote.Controllers
{
    [VerifyUser]
    public class SpoiledController : Controller
    {
        public ActionResult Index(int? id)
        {
            if(id == null) return RedirectToAction("Index", "Roster");

            ViewBag.SpoiledReasonList = ListMethods.SpoiledReasonList();

            return View(VoterDataMethods.SingleVoter(id));
        }

        // Spoil a Ballot
        public ActionResult SpoilBallot(int BarCode, int SpoiledReasonID)
        {
            bool result = VoterDataMethods.SpoilABallot(BarCode, SpoiledReasonID);

            return RedirectToAction("Index", "Roster");
        }
    }
}

EVoteTemplateLINQ/Views/Roster/FullSearch.cshtml
@model IEnumerable<EVote.DataModels.VoterDataModel>

@{
    ViewBag.Title = "Roster of Voter Activity";
}

<br /><br />
<div class="container">
    <div class="col-md-6 col-sm-4" style="text-align:center; vertical-align:middle;">
        <br />
        <h3 style="color:grey; text-shadow: 1px 1px lightgrey;">Roster of Voter Activity</h3>
    </div>
    <div class="col-md-6 col-sm-8" style="font-size:20px;">
        <table class="form-group">
            <tr>
                <td style="text-align:right; padding-right:10px; width:120px;">Roll </td>
                <td style="padding-bottom:6px; width:200px;"> <input type="text" id="txtRollNumber" style="width:100%;" class="form-control"/></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td style="text-align:right; padding-right:10px; width:120px;">Last </td>
                <td style="padding-bottom:6px;"> <input type="text" id="txtLastName" style="width:100%;" class="form-control"/></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td style="text-align:right; padding-right:10px; width:120px;">First </td>
                <td style="padding-bottom:6px;"> <input type="text" id="txtFirstName" style="width:100%;" class="form-control"/></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td style="text-align:right; padding-right:10px; width:120px;">Birth Year </td>
                <td style="padding-bottom:6px;"> <input type="text" id="txtDOBString" style="width:100%;" class="form-control"/></td>
                <td style="padding-left:12px;">
                    <a id="btnGo" href="#" class="btn btn-success" onclick="LoadListModelAjax()" data="Roster">Go</a>
                </td>
                <td style="padding-left:12px;">
                    <a href="#" class="btn btn-danger" onclick="ClearList()">Reset</a>
                </td>
            </tr>
        </table>
    </div>
</div>


<div class="container" style="clear:both;">    
    <div id="myListDiv">@Html.Partial("_List", Model)</div>
    <div id="loadingSpinner" style="text-align:center; display:none;">
        <div class="large progress" style="background-color:white; box-shadow:none;"><div></div></div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        // Initialize page features
        $(function () {
            SetKeyDownModel();

            $('#loadingSpinner').hide();
        });
    </script>
}

EVoteTemplateLINQ/Views/Roster/_List.cshtml
@model IEnumerable<EVote.DataModels.VoterDataModel>


@if (ViewBag.EmptyList >= 1)
{
    <p>@ViewBag.EmptyList Voters</p>

    <table class="table">
        @foreach (var item in Model)
        {
            <tr>
                <td style="width:100px;">
                    @Html.ActionLink("Signature", "RosterResult", "Signature", new { barCode = item.BarCode }, new { @class = "btn btn-default" })
                </td>
                <td style="padding-right:5px; width:120px; text-align:right;">
                    <span style="color:gray;">Name </span>
                </td>
                <td style="padding-left:0px; width:200px;">
                    <strong>@Html.DisplayFor(modelItem => item.LastName)</strong>
                    <br />
                    @Html.DisplayFor(modelItem => item.FirstName)
                    @Html.DisplayFor(modelItem => item.MiddleName)
                    @Html.DisplayFor(modelItem => item.Generation)
                </td>
                <td style="padding-right:5px; width:120px; text-align:right;">
                    <span style="color:gray;">Date of Birth</span>
                </td>
                <td style="padding-left:0px; ">
                    @item.DOB.ToString().Substring(0, item.DOB.ToString().IndexOf(" ") + 1)
                </td>
                @if (Session["ShowDistrict"].ToString() == "True")
                {
                    <td style="padding-right:5px; width:120px; text-align:right;">
                        <span style="color:gray;">District</span>
                    </td>
                    <td style="padding-left:0px; width:100px;">
                        @Html.DisplayFor(modelItem => item.DistrictName)
                    </td>
                }
                else
                {
                    <td style="padding-right:5px; width:70px; text-align:right;"></td>
                    <td style="padding-left:0px; width:100px;"></td>
                }
            </tr>

            <tr>
                <td style="border-top: 0px none white; padding-top:0px;">
                    @if (Session["Spoilable"].ToString() == "True")
                    {
                        @Html.ActionLink("Spoil Ballot", "Index", "Spoiled", new { id = item.BarCode }, new { @class = "btn btn-default" })
                    }
                    @Html.HiddenFor(modelItem => item.DOBSearch)
                    @Html.HiddenFor(modelItem => item.LogCode)
                </td>
                <td style="border-top: 0px none white; padding-top:0px; padding-right:5px; width:50px; text-align:right;">
                    <span style="color:gray;">Voted: </span>
                </td>
                <td style="border-top: 0px none white; padding-top:0px; padding-left:0px;">
                    @Html.DisplayFor(modelItem => item.LogDescription)
                </td>
                <td style="border-top: 0px none white; padding-top:0px;  padding-right:5px; width:50px; text-align:right;">
                    <span style="color:gray;">Date/Time:</span>
                </td>
                <td style="border-top: 0px none white; padding-top:0px; padding-left:0px;">
                    @if (Session["Registration"].ToString() != "True")
                    {
                        @Html.DisplayFor(modelItem => item.LogDate)
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.RegisteredDate)                        
                    }                    
                    @*@{
                          // DATE TIME CONVERSION FROM TIMESTAMP IS NOT CORRECT
                          long longvar = BitConverter.ToInt64(item.timestamp, 0);
                          //DateTime dateTimeVar = new DateTime(1980, 1, 1).AddMilliseconds(longvar);
                          DateTime dateTimeVar = DateTime.FromBinary(longvar);
                          @Html.Raw(dateTimeVar.ToShortDateString());
                        }*@
                </td>
                <td style="border-top: 0px none white; padding-top:0px;  padding-right:5px; width:100px; text-align:right;">
                    <span style="color:gray;">Voted at: </span>
                </td>
                <td style="border-top: 0px none white; padding-top:0px; padding-left:0px;">
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
            </tr>
        }

        @*Only show paging features when displaying an unfiltered list*@
        @if(ViewBag.CurrentPage != -1)
        {
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td colspan="3">
                    <table>
                        <tr>
                            <td style="border: 0 none white;">@Html.ActionLink("Prev", "Index", "Roster", new { page = ViewBag.CurrentPage - 1 }, new { @class = "btn btn-default" })</td>
                            <td style="border: 0 none white;">Page @ViewBag.CurrentPage of @ViewBag.TotalPages</td>
                            <td style="border: 0 none white;">@Html.ActionLink("Next", "Index", "Roster", new { page = ViewBag.CurrentPage + 1 }, new { @class = "btn btn-default" })</td>
                        </tr>
                    </table>
                </td>
                <td></td>
                <td></td>
            </tr>
        }

    </table>
}
else
{
    <div class="col-sm-4 pull-right">
        <p style="font-size:1.5em; color:red; font-weight:600;">No Voters Found</p>
    </div>
}