EVoteTemplateLINQ/Controllers/RosterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EVote.DataModels;
using EVote.DataMethods;
using EVote.Filters;
using EVote.Extensions;

namespace EVote.Controllers
{
    [VerifyUser]
    public class RosterController : Controller
    {
        ConfigurationModel _Session = ConfigurationMethods.SessionConfigs();

        // GET: Roster
        public ActionResult Index(int? page)
        {
            return View("FullSearch", InitializeRoster(page));
        }

        // Full name at date search page
        public ActionResult FullSearch(int? page)
        {
            return View(InitializeRoster(page));
        }

        // Pull most recent voters page by page
        public IEnumerable<VoterDataModel> InitializeRoster(int? page)
        {
            // Initialize page number
            if (page.IsNull()) page = 1;

            int size = Int32.Parse(Session["PageSize"].ToString()); // Set to session varriable

            IEnumerable<VoterDataModel> voterRoster;

            // Get the list of voters or voters from a specific site
            if (Session["SiteOnlyRoster"].ToString() == "True")
            {
                var site = Session["Username"].ToString();
                voterRoster = VoterDataMethods.RosterBySiteList(site);
            }
            else
            {
                voterRoster = VoterDataMethods.RosterList();
            }

            // Check for empty list
            ViewBag.EmptyList = VoterDataMethods.VoterCount(voterRoster);

            int maxPage = (ViewBag.EmptyList / size) + 1;            

            // set page limits
            if (page < 1) page = 1;
            if (page > maxPage) page = maxPage;

            // Set page counter display
            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = maxPage;

            // Returned a paged list of voters
            if (Session["Registration"].ToString() != "True")
            {
                return voterRoster.OrderByDescending(o => o.LogDate).Skip((int)(page - 1) * size).Take(size);
            }
            else
            {                
                return voterRoster.OrderByDescending(o => o.RegisteredDate).Skip((int)(page - 1) * size).Take(size);
            }                
        }

        // returns the partial view of voters from a full name at date search
        public ActionResult VoterExtendedSearch(string strRoll, string strLastName, string strFirstName, string strDate)
        {
            // Get the list of voters
            IEnumerable<VoterDataModel> voterRoster;
            if (Session["SiteOnlyRoster"].ToString() == "True")
            {
                var site = Session["Username"].ToString();
                voterRoster = VoterDataMethods.RosterSiteSearch(strRoll, strLastName, strFirstName, strDate, site);
            }
            else
            {
                voterRoster = VoterDataMethods.RosterSearch(strRoll, strLastName, strFirstName, strDate);
            }

            // Check for empty list
            ViewBag.EmptyList = VoterDataMethods.VoterCount(voterRoster);

            return PartialView("_List", voterRoster.OrderByDescending(o => o.LogDate));
        }

        public ActionResult VoterModelSearch(VoterSearchModel search)
        {
            // Get the list of voters            
            // Get the list of voters            
            IEnumerable<VoterDataModel> voterRoster;
            if (Session["SiteOnlyRoster"].ToString() == "True")
            {
                var site = Session["Username"].ToString();
                voterRoster = VoterDataMethods.RosterSiteModelSearch(search, site);
            }
            else
            {
                voterRoster = VoterDataMethods.RosterModelSearch(search);
            }

            // Check for empty list
            if (voterRoster != null) ViewBag.EmptyList = voterRoster.Count();
            else ViewBag.EmptyList = 0;

            return PartialView("_List", voterRoster.OrderByDescending(o => o.LogDate));
        }
    }
}

EVoteTemplateLINQ/Controllers/SignatureController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Drawing.Imaging;
using System.Text;
using SuperSignature;
using EVote.DataMethods;
using EVote.DataModels;
using EVote.Filters;

namespace EVote.Controllers
{
    [VerifyUser]
    public class SignatureController : Controller
    {
        public ActionResult Index(int? barCode)
        {
            // New more compact method for checking if user is logged in
            //if (Session["UserID"] == null) return RedirectToAction("Login", "Home");

            //if (barCode != null)
            //{
                //Session["CheckNetwork"] = _EVote.tblWebConfigs.Where(o => o.ConfigSetting == "SignatureCheckNetwork").FirstOrDefault().ConfigValue;

                VoterDataModel tVoter = VoterDataMethods.SingleVoter(barCode);
                ViewBag.BirthDateString = tVoter.DOB.ToString().Substring(0, tVoter.DOB.ToString().IndexOf(" ") + 1);
                return View(tVoter);
            //}
            //else
            //{
            //    return RedirectToAction("Index","Voter");
            //}
        }

        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            // Get BarCode from hidden field
            string strBarCode = Request["BarCode"];
            string signData = Request["ctlSignature_data"];
            string signDataSmooth = Request["ctlSignature_data_smooth"];

            // Get voter record from BarCode
            VoterDataModel tVoter = VoterDataMethods.SingleVoter(Int32.Parse(strBarCode));

            // Create bitmap object from signature control
            Bitmap bmpSign = GetSignatureBitmap(signData, signDataSmooth);

            FileContentResult result;

            using (var memStream = new System.IO.MemoryStream())
            {
                if (bmpSign != null)
                {
                    // Check if voter actually signed
                    if (bmpSign.Height == 200 && bmpSign.Width == 650)
                    {
                        // Save bitmap object to file
                        bmpSign.Save(HttpContext.Server.MapPath("~/Signatures/" + strBarCode + ".jpg"), ImageFormat.Jpeg);
                    }
                    else
                    {
                        // Get voter birthdate               
                        ViewBag.BirthDateString = tVoter.DOB.ToString().Substring(0, tVoter.DOB.ToString().IndexOf(" ") + 1);
                        // Return to signature page
                        return RedirectToAction("Index", tVoter);
                    }
                    result = this.File(memStream.GetBuffer(), "image/jpg");
                }
            }

            // Pass signed image location to next page
            ViewBag.SignFileURL = "../Signatures/" + strBarCode + ".jpg";
            // Pass voters ID to next page
            ViewBag.BarCode = strBarCode;

            ViewBag.Signed = "Signature";
            // Redirect to signature review page
            if (Session["BallotNumOnSig"].ToString() == "False")
            {
                return RedirectToAction("SignResult", tVoter);
            }
            else
            {
                return RedirectToAction("SignResultBallot", tVoter);
            }

        }

        public JsonResult SaveSignature(FormCollection collection)
        {
            string newURL;

            // Get BarCode from hidden field
            string strBarCode = Request["BarCode"];
            string signData = Request["ctlSignature_data"];
            string signDataSmooth = Request["ctlSignature_data_smooth"];

            // Get voter record from BarCode
            VoterDataModel tVoter = VoterDataMethods.SingleVoter(Int32.Parse(strBarCode));

            // Create bitmap object from signature control
            Bitmap bmpSign = GetSignatureBitmap(signData, signDataSmooth);

            FileContentResult result;

            using (var memStream = new System.IO.MemoryStream())
            {
                if (bmpSign != null)
                {
                    // Check if voter actually signed
                    if (bmpSign.Height == 200 && bmpSign.Width == 650)
                    {
                        // Save bitmap object to file
                        bmpSign.Save(HttpContext.Server.MapPath("~/Signatures/" + strBarCode + ".jpg"), ImageFormat.Jpeg);
                    }
                    else
                    {
                        // Get voter birthdate               
                        ViewBag.BirthDateString = tVoter.DOB.ToString().Substring(0, tVoter.DOB.ToString().IndexOf(" ") + 1);
                        // Return to signature page
                        //return RedirectToAction("Index", tVoter);
                        newURL = "/epollbook/Signature/Index?barCode=" + strBarCode;
                    }
                    result = this.File(memStream.GetBuffer(), "image/jpg");
                }
            }

            // Pass signed image location to next page
            ViewBag.SignFileURL = "../Signatures/" + strBarCode + ".jpg";
            // Pass voters ID to next page
            ViewBag.BarCode = strBarCode;

            ViewBag.Signed = "Signature";
            string root = Url.Content("~/");
            // Redirect to signature review page
            if (Session["BallotNumOnSig"].ToString() == "False")
            {
                //return RedirectToAction("SignResult", tVoter);
                newURL = root + "Signature/SignResult?barCode=" + strBarCode;
            }
            else
            {
                //return RedirectToAction("SignResultBallot", tVoter);
                newURL = root + "Signature/SignResultBallot?barCode=" + strBarCode;
            }

            //JavaScriptSerializer js = new JavaScriptSerializer();
            return Json(newURL, JsonRequestBehavior.AllowGet); ;
        }

        private Bitmap GetSignatureBitmap(string signData, string signDataSmooth)
        {
            MouseSignature ctlSignature = new MouseSignature();

            byte[] arrayOfBytes = Convert.FromBase64String(signData);
            signData = Encoding.UTF8.GetString(arrayOfBytes);

            byte[] arrayOfBytesSmooth = Convert.FromBase64String(signDataSmooth);
            signDataSmooth = Encoding.UTF8.GetString(arrayOfBytesSmooth);

            ctlSignature.SignDataSmooth = signDataSmooth;

            Bitmap bmpSign = ctlSignature.GenerateSignature(signData, "");

            return bmpSign;
        }

        public ActionResult SignResult(string BarCode)
        {
            // New more compact method for checking if user is logged in
            //if (Session["UserID"] == null) return RedirectToAction("Login", "Home");
            if (BarCode == null) return RedirectToAction("Index", "Voter");

            ViewBag.BarCode = BarCode;
            ViewBag.SignFileURL = "../Signatures/" + BarCode + ".jpg";
            VoterDataModel tVoter = VoterDataMethods.SingleVoter(Int32.Parse(BarCode));
            return View(tVoter);
        }

        public ActionResult SignResultBallot(string BarCode)
        {
            // New more compact method for checking if user is logged in
            //if (Session["UserID"] == null) return RedirectToAction("Login", "Home");
            if (BarCode == null) return RedirectToAction("Index", "Voter");

            ViewBag.BarCode = BarCode;
            ViewBag.SignFileURL = "../Signatures/" + BarCode + ".jpg";
            VoterDataModel tVoter = VoterDataMethods.SingleVoter(Int32.Parse(BarCode));
            return View(tVoter);
        }

        public ActionResult RosterResult(string BarCode)
        {
            // New more compact method for checking if user is logged in
            //if (Session["UserID"] == null) return RedirectToAction("Login", "Home");
            if (BarCode == null) return RedirectToAction("Index", "Voter");

            ViewBag.BarCode = BarCode;
            ViewBag.SignFileURL = "../Signatures/" + BarCode + ".jpg";
            VoterDataModel tVoter = VoterDataMethods.SingleVoter(Int32.Parse(BarCode));
            return View(tVoter);

        }

        public ActionResult SignInFinish(int? BarCode, int? BallotNumber)
        {
            // New more compact method for checking if user is logged in
            //if (Session["UserID"] == null) return RedirectToAction("Login", "Home");
            if (BarCode == null) return RedirectToAction("Index", "Voter");

            bool result = false;
            // Roll ID 9 is early voting
            if (Convert.ToInt32(Session["RoleID"]) == 9)
            {
                result = VoterDataMethods.UpdateEarlyVoter((int)BarCode, Session["UserName"].ToString(), BallotNumber);
            }
            else
            {
                result = VoterDataMethods.UpdateVotedAtPolls((int)BarCode, Session["UserName"].ToString(), BallotNumber);
            }

            return RedirectToAction("Index", "Voter");
        }
    }
}

EVoteTemplateLINQ/Views/Signature/Index.cshtml
@model EVote.DataModels.VoterDataModel


    <form id="SignatureForm" method="post" action="~/Signature/Index">
        <br /><br />
        @*@if (Session["CheckNetwork"].ToString() == "True")
        {
            <a id="SaveSig" href="#" class="btn btn-success" onclick="SaveSignature()">Save Signature</a>
        }
        else
        {
            <input type="submit" value="Save Signature" class="btn btn-success" />
        }*@
        <input type="submit" value="Save Signature" class="btn btn-success" />
        
        <input type="hidden" id="bolConnection" value="false" />        

        <a href="~/Voter/Index" class="btn btn-danger">Cancel</a>

        <a href="~/Signature?barCode=@Model.BarCode" class="btn btn-danger">Clear</a>
        <br /><br />

        <div class="col-md-6" style="font-size:1.2em;">
            Voter Sign in Page for:
        </div>

        <hr style="margin:3px 0 12px 0; padding:0 0 0 0; clear:both;" />
        
        <div class="col-md-6">
            @Html.DisplayFor(model => model.FirstName)
            @Html.DisplayFor(model => model.MiddleName)
            @Html.DisplayFor(model => model.LastName)
            @Html.DisplayFor(model => model.Generation)
        </div>
        <div class="col-md-4">
            DOB @ViewBag.BirthDateString
        </div>
        <div style="clear:both;"></div>

        <div style="height:100px;">&nbsp;</div>

        <div class="row">
            <div class="col-md-6 col-centered" style="margin: 0 auto;">
                <div style="font-size:0.8em;">
                    <i>Voter Sign Here</i>
                </div>
                <div id='ctlSignature_Container' style='width: 650px; height: 200px; margin: 10px; position: relative;'>
                    @*<script language="javascript" type="text/javascript">
                    var ieVer = getInternetExplorerVersion();
                    if (isIE) {
                        if (ieVer >= 9.0)
                            isIE = false;
                    }

                    if (isIE) {
                        document.write("<div ID='ctlSignature' style='width:450px;height:300px;'></div>");
                    }
                    else {
                        document.write("<canvas id='ctlSignature' width='450' height='300' style='left: 0px; top: 0px; position: absolute;'></canvas>");
                    }
                    </script>*@

                    <canvas id='ctlSignature' width='650' height='200' style='left: 0px; top: 0px; position: absolute;'></canvas>
                </div>
                <div id='ctlSignature_toolbar' style='display: block; left: 10px; height: 20px; width: 650px;
    position: relative; background-color: transparent;'>
                    <input type="button" id='ctlSignature_resetbutton' value="Reset" style='cursor: pointer;
        float: right; display:none;' /><div id='ctlSignature_status' style='color: blue; font-family: verdana;
            font-size: 12px; float: right; margin-right: 5px; display:none;'>
                    </div>
                </div>
                @Html.HiddenFor(m => m.BarCode)
                <input type='hidden' id='ctlSignature_data' name='ctlSignature_data' value='' />
                <input type='hidden' id='ctlSignature_data_smooth' name='ctlSignature_data_smooth' value='' />
                @section scripts{
                    <script type="text/javascript">
                        var result = null;
                        var objctlSignature;

                        $(document).ready(function () {
                            // Create Signature object and set parameters
                            objctlSignature = new SuperSignature({
                                SignObject: "ctlSignature",
                                SignWidth: "650",
                                SignHeight: "200",
                                ImageScaleFactor: "1",
                                Enabled: "true",
                                SmoothSign: true,
                                TransparentSign: false,
                                BackColor: "#DFE5ED",
                                Visible: "true",
                                RequiredPoints: 50,
                                SignStatusBar: false,
                                SignRequired: true,
                                SuccessMessage: "Signature OK.",
                                StartMessage: "Please sign.",
                                ErrorMessage: "Please continue your signature.",
                                SignShowImageBorder: true,
                                BorderColor: "#DCDCDC",
                                BorderStyle: "solid",
                                BorderWidth: "2px",
                                PenColor: "#000000",
                                PenSize: 2,
                                jQueryEvent: false,
                                forceMouseEvent: true
                            });

                            // Initialize the Signature Object
                            try { objctlSignature.Init(); } catch (ex) { alert(ex.description); }

                        });

                        // PenCursor : "pen.cur"  // choose path relative to ss.js and provide your file                                           

                    </script>
                }
            </div>
        </div>
        <div style="clear:both;"></div>
</form>

EVoteTemplateLINQ/Views/Signature/RosterResult.cshtml
@model EVote.DataModels.VoterDataModel

<br /><br />

<div class="col-md-3" style="font-size:1.2em;">
    Verify Signature for:
</div>

<hr style="margin:3px 0 12px 0; padding:0 0 0 0; clear:both;" />

<div class="col-md-8">
    @Html.DisplayFor(model => model.FirstName)
    @Html.DisplayFor(model => model.MiddleName)
    @Html.DisplayFor(model => model.LastName)
    @Html.DisplayFor(model => model.Generation)
</div>

<div class="container">&nbsp;</div>
<br />
    <div class="container">
        <div class="col-md-6">
            <br />
            <div style="color:red; font-size:0.8em;">
                <i>Voter's Signature</i>
            </div>
            <img src="@ViewBag.SignFileURL" />
        </div>
    </div>

    <br />
    <div class="container">
        @Html.ActionLink("Signature Ok", "Index", "Roster", new { barCode = ViewBag.BarCode }, new { @class = "btn btn-success" })
        @Html.ActionLink("Cancel", "Index", "Roster", new { barCode = ViewBag.BarCode }, new { @class = "btn btn-danger" })
    </div>
    

EVoteTemplateLINQ/Views/Signature/SignResult.cshtml
@model EVote.DataModels.VoterDataModel

<br /><br />

<div class="col-md-3" style="font-size:1.2em;">
    Verify Signature for:
</div>

<hr style="margin:3px 0 12px 0; padding:0 0 0 0; clear:both;" />

<div class="col-md-8">
    @Html.DisplayFor(model => model.FirstName)
    @Html.DisplayFor(model => model.MiddleName)
    @Html.DisplayFor(model => model.LastName)
    @Html.DisplayFor(model => model.Generation)
</div>

<div class="container">&nbsp;</div>
<br />
    <div class="container">
        <div class="col-md-6">
            <br />
            <div style="color:red; font-size:0.8em;">
                <i>Voter's Signature</i>
            </div>
            <img src="@ViewBag.SignFileURL" />
        </div>
    </div>

    <br />
    <div class="container">
        @Html.ActionLink("Signature Ok", "SignInFinish", "Signature", new { barCode = ViewBag.BarCode }, new { @class = "btn btn-success" })
        @Html.ActionLink("Cancel/Re-Sign", "Index", "Signature", new { barCode = ViewBag.BarCode }, new { @class = "btn btn-danger" })
    </div>
    

EVoteTemplateLINQ/Views/Signature/SignResultBallot.cshtml
@model EVote.DataModels.VoterDataModel

<br /><br />

<div class="col-md-3" style="font-size:1.2em;">
    Verify Signature for:
</div>

<hr style="margin:3px 0 12px 0; padding:0 0 0 0; clear:both;" />

<div class="col-md-8">
    @Html.DisplayFor(model => model.FirstName)
    @Html.DisplayFor(model => model.MiddleName)
    @Html.DisplayFor(model => model.LastName)
    @Html.DisplayFor(model => model.Generation)
</div>

<div class="container">&nbsp;</div>
<br />
    <div class="container">
        <div class="col-md-6">
            Ballot Number
            <input id="BallotNumber" type="text" class="form-control" />
            <br />
            <div style="color:red; font-size:0.8em;">
                <i>Voter's Signature</i>
            </div>
            <img src="@ViewBag.SignFileURL" />
        </div>
    </div>

    <br />
    <div class="container">
        @Html.ActionLink("Signature Ok", "SignInFinish", "Signature", new { barCode = ViewBag.BarCode }, new { @class = "btn btn-success", @id = "btnSave", @onClick = "CheckBallotNumber()" })
        @Html.ActionLink("Cancel/Re-Sign", "Index", "Signature", new { barCode = ViewBag.BarCode }, new { @class = "btn btn-danger" })
    </div>

@section scripts{
    <script type="text/javascript">
        var CheckBallotNumber = function () {
            var balNo = $('#BallotNumber').val();
            // Check for valid ballot number
            if (Math.floor(balNo) == balNo && $.isNumeric(balNo))
            {
                if ($('#tempSave').length > 0) {
                    // Retrieve stored address
                    $('#btnSave').attr('href', $('#tempSave').attr('href') + '&BallotNumber=' + balNo);
                }
                else {
                    $('#btnSave').attr('href', $('#btnSave').attr('href') + '&BallotNumber=' + balNo);
                }
                console.log($('#btnSave').attr('href'));
            }
            else
            {
                // Store btnSave address
                $('<input>').attr({
                    type: 'hidden',
                    id: 'tempSave',
                    name: 'tempSave'
                }).appendTo('form');
                $('#tempSave').attr('href', $('#btnSave').attr('href'));

                $('#btnSave').attr('href', "#");
                alert("Please Enter a Valid Ballot Number");
            }
        };
    </script>
}