EVoteTemplateLINQ/Controllers/AbsenteeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EVote.DataModels;
using EVote.DataMethods;
using EVote.Filters;

namespace EVote.Controllers
{
    [VerifySuperUser]
    public class AbsenteeController : Controller
    {
        //private static EVoteVoterDataDataContext _EVote = new EVoteVoterDataDataContext();

        public ActionResult Index()
        {
            return View("FullSearch");
        }

        // Full name and date search page
        public ActionResult FullSearch()
        {
            return View();
        }

        // returns the partial view of voters from a full name at date search
        public ActionResult VoterExtendedSearch(string strRoll, string strLastName, string strFirstName, string strDate)
        {
            // Get the list of voters            
            IEnumerable<VoterDataModel> voterList = VoterDataMethods.FullSearch(strRoll, strLastName, strFirstName, strDate);

            // Check for empty list
            if (voterList != null) ViewBag.EmptyList = voterList.Count();
            else ViewBag.EmptyList = 0;

            return PartialView("_List", voterList);
        }

        public ActionResult VoterModelSearch(VoterSearchModel search)
        {
            // Get the list of voters            
            IEnumerable<VoterDataModel> voterList = VoterDataMethods.ModelSearch(search);

            // Check for empty list
            if (voterList != null) ViewBag.EmptyList = voterList.Count();
            else ViewBag.EmptyList = 0;

            return PartialView("_List", voterList);
        }

        // Edit Voter Details Page
        public ActionResult Edit(int BarCode)
        {
            // Pass voter details to view
            var voter = VoterDataMethods.SingleVoter(BarCode);

            // Set drop down list objects
            ViewBag.DistrictList = ListMethods.DistrictList(null);
            ViewBag.LogCodeList = ListMethods.AbsenteeLogCodeList(voter.LogCode);
            //ViewBag.LogCodeList = ListMethods.LogCodeList(null);
            ViewBag.SitesList = ListMethods.SitesList(0);

            // Display the full voter status description
            ViewBag.VoterStatus = LogCodeMethods.LogDescription(voter.LogCode);

            return View(voter);
        }

        [HttpPost]
        public ActionResult Edit(VoterDataModel voterFromForm)
        {
            if (Session["Username"] != null)
            {
                voterFromForm.UserName = Session["Username"].ToString();
            }

            // Update the changes submitted from the client
            var result = VoterDataMethods.UpdateAbsenteeVoter(voterFromForm);

            if (result == true)
            {
                ViewBag.Results = "Voter saved successfully";
                ViewBag.SaveStatus = "True";
            }
            else
            {
                ViewBag.Results = "Voter save unsuccessful";
            }

            // Reset the drop down lists
            ViewBag.DistrictList = ListMethods.DistrictList(null);
            ViewBag.LogCodeList = ListMethods.AbsenteeLogCodeList(null);
            ViewBag.SitesList = ListMethods.SitesList(0);

            // Display the full voter status description
            ViewBag.VoterStatus = LogCodeMethods.LogDescription(voterFromForm.LogCode);

            // Pass voter object to view
            return View(VoterDataMethods.SingleVoter(voterFromForm.BarCode));
            //return RedirectToAction("Index");
        }
    }
}

EVoteTemplateLINQ/Controllers/VoterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EVote.DataModels;
using EVote.DataMethods;
using EVote.Filters;
using EVote.Factories;

namespace EVote.Controllers
{
    [VerifyUser]
    public class VoterController : Controller
    {
        ConfigurationModel _Session = ConfigurationMethods.SessionConfigs();

        public ActionResult Index(string id)
        {
            // Change the default behavior based on config setting
            if (Session["SearchDate"].ToString() == "True")
            {
                // Default to the Date Search page
                if (id == "fullname") return View("FullSearch");
                else
                {
                    SetDateLists();
                    return View("DateSearch");
                }
            }
            else
            {
                // Default to the Name Search page
                if (id == "date")
                {
                    SetDateLists();
                    return View("DateSearch");
                }
                else
                {
                    return View("FullSearch");
                }                
            }
        }

        // Full name and date search page
        public ActionResult FullSearch()
        {
            //ViewBag.Results = string.Format("../Home/Login", HttpContext.Request.Url.AbsolutePath);
            ViewBag.Results = Url.Content("~/").ToString();
            return View();
        }

        // Search by birth date page
        public ActionResult DateSearch()
        {
            SetDateLists();

            return View();
        }

        // Get the Month, Day, and Year lists for the birthday search page
        public void SetDateLists()
        {
            int startYear = 1900; // Initialize Date Range
            int defaultAge = 20; // This sets the value the Year drop down displays when the page loads // Example: Now - 20 = 1997

            // Get list of years
            ViewBag.BirthYearList = ListMethods.BirthYearList(startYear, defaultAge);

            // Get list of months 
            if (Session["MonthNames"].ToString() == "True")
            {
                ViewBag.BirthMonthList = ListMethods.BirthMonthNames();
            }
            else
            {
                ViewBag.BirthMonthList = ListMethods.BirthMonthList();
            }

            // Get list of Days in each month
            ViewBag.BirthDayList = ListMethods.BirthDayList();
        }

        // returns the partial view of voters from a full name at date search
        public ActionResult VoterExtendedSearch(string strRoll, string strLastName, string strFirstName, string strDate)
        {
            // Get the list of voters            
            IEnumerable<VoterDataModel> voterList = VoterDataMethods.FullSearch(strRoll, strLastName, strFirstName, strDate);

            List<VoterDataModel> newVoterList = new List<VoterDataModel>();
            foreach (var voter in voterList)
            {
                voter.ValidLocation = ValidateVotersDistrict(voter);
                newVoterList.Add(voter);
            }

            // Check for empty list
            if (voterList != null) ViewBag.EmptyList = voterList.Count();
            else ViewBag.EmptyList = 0;

            ViewBag.NoDistrictNoVote = (bool)(Session["NoDistrictNoVote"].ToString() == "True");
            ViewBag.DistrictSignIn = (bool)(Session["DistrictSignIn"].ToString() == "True");
            ViewBag.ShowDistrict = (bool)(Session["ShowDistrict"].ToString() == "True");

            return PartialView("_List", voterList);
        }

        public ActionResult VoterModelSearch(VoterSearchModel search)
        {
            //Session.Abandon();

            // Get the list of voters            
            IEnumerable<VoterDataModel> voterList = VoterDataMethods.ModelSearch(search);

            List<VoterDataModel> newVoterList = new List<VoterDataModel>();
            foreach (var voter in voterList)
            {
                voter.ValidLocation = ValidateVotersDistrict(voter);
                newVoterList.Add(voter);
            }

            // Check for empty list
            if (voterList != null) ViewBag.EmptyList = voterList.Count();
            else ViewBag.EmptyList = 0;

            ViewBag.NoDistrictNoVote = (bool)(Session["NoDistrictNoVote"].ToString() == "True");
            ViewBag.DistrictSignIn = (bool)(Session["DistrictSignIn"].ToString() == "True");
            ViewBag.ShowDistrict = (bool)(Session["ShowDistrict"].ToString() == "True");

            return PartialView("_List", voterList);
        }

        // returns the partial view of voters from a birth date search
        public ActionResult VoterDateSearch(string strDate)
        {
            //Session["UserID"] = null;
            //Session.Abandon(); 

            // Get the list of voters            
            IEnumerable<VoterDataModel> voterList = VoterDataMethods.DateSearch(strDate);

            List<VoterDataModel> newVoterList = new List<VoterDataModel>();
            foreach (var voter in voterList)
            {
                voter.ValidLocation = ValidateVotersDistrict(voter);
                newVoterList.Add(voter);
            }

            // Check for empty list
            if (voterList != null) ViewBag.EmptyList = voterList.Count();
            else ViewBag.EmptyList = 0;

            ViewBag.NoDistrictNoVote = (bool)(Session["NoDistrictNoVote"].ToString() == "True");
            ViewBag.DistrictSignIn = (bool)(Session["DistrictSignIn"].ToString() == "True");
            ViewBag.ShowDistrict = (bool)(Session["ShowDistrict"].ToString() == "True");

            return PartialView("_List", voterList);
        }

        // Get Json list of days in month 
        // Json list will be used to stuff the client side drop down list
        // Year parameter added for calculating leap years
        public virtual JsonResult BirthDayListJson(int intMonth, int intYear)
        {
            var DayList = ListMethods.BirthDayLeap(intMonth, intYear);

            // Convert list object to Json object
            //string jsonList = new JavaScriptSerializer().Serialize(DayList);
            return Json(DayList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MonthsOfTheYear(string selectedmonth)
        {
            var list = ListMethods.BirthMonthNames();
            return PartialView("_MonthsOfYear", new SelectList(list, "Value", "Text", selectedmonth));
        }

        public ActionResult DaysOfTheMonth(string selectedday)
        {
            var list = ListMethods.BirthDayList();            
            return PartialView("_DaysOfMonth", new SelectList(list, "Value", "Text", selectedday));
        }

        public ActionResult BirthYears(string selectedyear)
        {
            int startYear = 1900; // Initialize Date Range
            int defaultAge = 18; // This sets the value the Year drop down displays when the page loads // Example: Now - 20 = 1997

            // Get list of years
            var list = ListMethods.BirthYearList(startYear, defaultAge);
            return PartialView("_BirthYears", new SelectList(list, "Value", "Text", selectedyear));
        }

        public ActionResult TestSearch()
        {
            return View();
        }

        // Edit Voter Details Page
        public ActionResult District(int BarCode)
        {
            //// Admins, Devs and SuperUsers can access this page
            //if (Convert.ToInt32(Session["RoleID"]) > 1)
            //{
                // Set drop down list objects
                ViewBag.DistrictList = ListMethods.DistrictList(null);
                ViewBag.LogCodeList = ListMethods.LogCodeList(null);
                ViewBag.SitesList = ListMethods.SitesList(0);

                // Pass voter details to view
                var voter = VoterDataMethods.SingleVoter(BarCode);

                // Display the full voter status description
                ViewBag.VoterStatus = LogCodeMethods.LogDescription(voter.LogCode);

                ViewBag.Error = "";
                return View(voter);
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Home");
            //}
        }

        [HttpPost]
        public ActionResult District(VoterDataModel voterFromForm)
        {
            if (Session["DistrictOnly"].ToString() == "True")
            {
                var result = ValidateVoterDistrict(voterFromForm);
                if (result != null)
                {
                    return result;
                }
            }
            else
            {
                // Vadiate birthdate since standard validation dosnt work            
                if (voterFromForm.ValidateBirthdate())
                {
                    // GEt new combo number
                    voterFromForm.ComboNo = DistrictMethods.GetDistrict(voterFromForm.District).ComboNo;

                    // Update the changes submitted from the client
                    var result = VoterDataMethods.UpdateVoter(voterFromForm);

                    if (result == true)
                    {
                        ViewBag.Results = "Voter saved successfully";
                    }
                    else
                    {
                        ViewBag.Results = "Voter save unsuccessful";
                    }
                }
                else
                {
                    ModelState.AddModelError("DOBSearch", "Enter a valid birthdate");
                }

                // Compare Site to selected district
                if (voterFromForm.District != 0)
                {
                    return RedirectToAction("Index", "Signature", new { barCode = voterFromForm.BarCode });
                }
            }

            // Reset the drop down lists

EVoteTemplateLINQ/Views/Absentee/FullSearch.cshtml
@{
    ViewBag.Title = "Absentee Lookup";
}

<br /><br />
<div class="container">
    <div class="col-md-6 col-sm-4" style="text-align:center; vertical-align:middle;">
        <br />
        <h3 style="color:grey; text-shadow: 1px 1px lightgrey;">Absentee Lookup</h3>
    </div>
    <div class="col-md-6 col-sm-8" style="font-size:20px;">
        <table class="form-group">
            <tr>
                <td style="text-align:right; padding-right:10px; width:120px;">Roll </td>
                <td style="padding-bottom:6px; width:200px;"> <input type="text" id="txtRollNumber" style="width:100%;" class="form-control"/></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td style="text-align:right; padding-right:10px; width:120px;">Last </td>
                <td style="padding-bottom:6px;"> <input type="text" id="txtLastName" style="width:100%;" class="form-control"/></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td style="text-align:right; padding-right:10px; width:120px;">First </td>
                <td style="padding-bottom:6px;"> <input type="text" id="txtFirstName" style="width:100%;" class="form-control"/></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td style="text-align:right; padding-right:10px; width:120px;">Birth Year</td>
                <td style="padding-bottom:6px;"> <input type="text" id="txtDOBString" style="width:100%;" class="form-control"/></td>
                <td style="padding-left:12px;">
                    <a id="btnGo" href="#" class="btn btn-success" onclick="LoadListModelAjax()" data="Absentee">Go</a>
                </td>
                <td style="padding-left:12px;">
                    <a href="#" class="btn btn-danger" onclick="ClearList()">Reset</a>
                </td>
            </tr>
            <tr>
                <td></td>
                <td colspan="4" style="font-size:0.8em;">
                    @*@Html.ActionLink("Use Date Search", "SearchBy", "Voter", new { type = "date" }, null)*@
                </td>
            </tr>
        </table>
    </div>
</div>

<div class="container">
    <div id="myListDiv"></div>
    <div id="loadingSpinner" style="text-align:center; display:none;">
        <div class="large progress" style="background-color:white; box-shadow:none;"><div></div></div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        // Set up keydown functions when page loads
        $(function () { SetKeyDownModel() });
    </script>
}

EVoteTemplateLINQ/Views/Absentee/_List.cshtml
@model IEnumerable<EVote.DataModels.VoterDataModel>


@if (ViewBag.EmptyList >= 1)
{
    <br /><br />
    <p>@ViewBag.EmptyList Voters Found</p>

<table class="table">
@foreach (var item in Model)
{
    <tr>
        <td style="width:100px;">            
            @Html.ActionLink("Select", "Edit", "Absentee", new { barCode = item.BarCode }, new { @class = "btn btn-default" })                
        </td>
        <td style="padding-right:5px; width:100px; text-align:right;">
            <span style="color:grey;">Name </span>
        </td>
        <td style="padding-left:0px; width:200px;">            
            <strong>@Html.DisplayFor(modelItem => item.LastName)</strong>
            <br />
            @Html.DisplayFor(modelItem => item.FirstName)
            @Html.DisplayFor(modelItem => item.MiddleName)
            @Html.DisplayFor(modelItem => item.Generation)
        </td>
        <td style="padding-right:5px; width:150px; text-align:right;">
            <span style="color:grey;">Address </span>
        </td>
        <td  style="padding-left:0px;">
            @Html.DisplayFor(modelItem => item.Address1)
            @Html.DisplayFor(modelItem => item.Address2)
            <br />
            @Html.DisplayFor(modelItem => item.City)
            @Html.DisplayFor(modelItem => item.State)
            @Html.DisplayFor(modelItem => item.Zip)
        </td>
        <td style="padding-right:5px; width:120px; text-align:right;">
            <span style="color:grey;">Birthdate </span>
        </td>
        <td  style="padding-left:0px;">
            @item.DOB.ToString().Substring(0, item.DOB.ToString().IndexOf(" ") + 1)
        </td>
    </tr>

    <tr>
        <td style="border-top: 0px none white; padding-top:0px;">
            @Html.HiddenFor(modelItem => item.DOBSearch)
            @Html.HiddenFor(modelItem => item.LogCode)
        </td>        
        <td style="border-top: 0px none white; padding-top:0px;  padding-right:5px; width:50px; text-align:right;">
            <span style="color:grey;">Roll No </span>
        </td>
        <td style="border-top: 0px none white; padding-top:0px; padding-left:0px;">            
            @Html.DisplayFor(modelItem => item.VoterID)
        </td>
        <td style="border-top: 0px none white; padding-top:0px;  padding-right:5px; width:150px; text-align:right;">
            <span style="color:grey;">Voting Status </span>
        @if (item.LogCode == 12)
        {
            <br />
            <span style="color:grey;">Where Voted </span>
            <br />
            <span style="color:grey;">Time </span>
        }
        </td>
        <td style="border-top: 0px none white; padding-top:0px; padding-left:0px;">            
            @Html.DisplayFor(modelItem => item.LogDescription)
        @if (item.LogCode == 12)
        {
            <br />
            @Html.DisplayFor(modelItem => item.UserName)
            <br />
            @Html.DisplayFor(modelItem => item.LogDate)
        }
        </td>
        @if (Session["ShowDistrict"].ToString() == "True")
        {
        <td style="border-top: 0px none white; padding-top:0px; padding-right:5px; width:50px; text-align:right;">
            <span style="color:grey;">District </span>
        </td>
        <td style="border-top: 0px none white; padding-top:0px; padding-left:0px;">
            @Html.DisplayFor(modelItem => item.DistrictName)
        </td>
        }
        else
        {
            <td style="border-top: 0px none white;">&nbsp;</td>
            <td style="border-top: 0px none white;">&nbsp;</td>
        }
    </tr>
}

</table>
}
else
{
    <div class="col-sm-4 pull-right">
        <p style="font-size:1.5em; color:red; font-weight:600;">No Voters Found</p>
    </div>
}